README.md

The previous link didn't show right when opened from a phone.

README: update video link

---

Cargo.lock
util/Cargo.toml
util/src/systemd.rs

@KillingSpark showed an a lot simpler way of using rustbus:
https://github.com/KillingSpark/rustbus/issues/49#issuecomment-732365837
Apply the suggested much better approach.

util: simplify rustbus usage in the systemd helper

---

Cargo.lock
resctl-demo/Cargo.toml
resctl-demo/src/agent.rs
resctl-demo/src/doc.rs
resctl-demo/src/doc/markup_rd.rs
resctl-demo/src/graph.rs
resctl-demo/src/journal.rs
resctl-demo/src/main.rs
resctl-demo/src/status.rs

This removes the last external dependency and will allow the whole suite to be built statically w/ musl.

Switch resctl-demo to use termion backend instead of the default ncurses

---

rd-hashd/src/logger.rs

To avoid compression affecting the IO rate, the logger calls btrfs tool to
disable compression. However, btrfs ignores it when mounted with
compress-force mount option and it can also get affected by device side
compression. Instead of asking btrfs to disable compression, pad log with
random data.

hashd: make log data random instead of turning off compression

---

resctl-bench-intf/src/args.rs
resctl-bench-intf/src/jobspec.rs
resctl-bench-intf/src/lib.rs
resctl-bench/src/bench.rs
resctl-bench/src/bench/hashd_params.rs
resctl-bench/src/bench/iocost_params.rs
resctl-bench/src/bench/iocost_qos.rs
resctl-bench/src/bench/storage.rs
resctl-bench/src/job.rs
resctl-bench/src/main.rs
resctl-bench/src/run.rs
util/src/json_file.rs

This will be used as the basis for building result analysis subcommands.

Bench formatting and subcommand handling improvements

---

resctl-bench/src/bench/iocost_qos.rs

Use the iolat_pcts covering both storage and protection runs and print write
latencies too.

bench: iocost-qos: fix iolat_pcts formatting

---

resctl-bench/src/bench/iocost_qos.rs
resctl-bench/src/bench/protection.rs
resctl-bench/src/bench/storage.rs
resctl-bench/src/study.rs

And other visiblity and cosmetic updates.

bench: storage, protection: report % of missing reports

---

resctl-bench/src/job.rs

The result files can be really big (>10M). Support g[un]zipping if the result file name ends with ".gz".

bench: support gzipp'ed result files

---

resctl-bench/src/job.rs

bench: fix compressed result writing

---

resctl-bench/src/bench/iocost_tune.rs
resctl-bench/src/job.rs

* Line fitting and solution computations improved.
* Prettier result printing.
* Remarks added to provide more context on the results.

Polish iocost-tune

---

util/src/storage_info.rs

* It didn't actually open the fwrev file and thus always was returning empty
string for fwrev.
* Make it return "<UNKNOWN>" if the model and/or fwrev can't be determined
instead of failing. This allows running resctl-bench on things like nbd
devices.

util: fix devname_to_model_fwrev_size()

---

resctl-bench/src/bench/iocost_tune.rs

* Set rlat/wlat for fixed vrate solutions.
* Implement inflection point offset.

bench: improve iocost-tune

---

rd-agent-intf/src/args.rs
rd-agent-intf/src/lib.rs
rd-agent-intf/src/sysreqs.rs
rd-agent/src/bench.rs
rd-agent/src/cmd.rs
rd-agent/src/main.rs
rd-agent/src/slices.rs
resctl-bench-intf/src/args.rs
resctl-bench-intf/src/jobspec.rs
resctl-bench/src/base.rs
resctl-bench/src/bench.rs
resctl-bench/src/bench/hashd_params.rs
resctl-bench/src/bench/iocost_qos.rs
resctl-bench/src/bench/iocost_tune/merge.rs
resctl-bench/src/bench/protection.rs
resctl-bench/src/bench/storage.rs
resctl-bench/src/job.rs
resctl-bench/src/merge.rs
resctl-bench/src/run.rs
util/src/storage_info.rs

So that benchmarks can be easily run w/ specific resource control as-is.

Improve passive mode handling

---

README.md

Update install instructions for Fedora

---

Cargo.lock
rd-util/Cargo.toml
rd-util/src/systemd.rs

I also had to bump vergen to a minor release due to a conflict with the new sysinfo.

Update rustbus to 0.17

---

rd-agent/src/side.rs

If `--linux-tar` is not set and `/usr/share/resctl-demo/linux.tar` exists, use that instead of downloading; if it doesn't, but `/usr/share/resctl-demo/linux.tar.xz` exists, use that (after decompressing it); if neither exist download.
Closes: #238

Use preinstalled kernel tarball if available

---

rd-agent/src/misc/sideloader.py

agent: remove reference to fb internal doc from sideloader.py

---

.github/workflows/ci.yaml
resctl-bench/src/merge.rs

For each pull request, build the project from source then run the test suite.

Build resctl-demo and run unit tests in GitHub CI

---

rd-util/src/storage_info.rs
resctl-bench/src/bench/iocost_tune.rs
resctl-bench/src/bench/iocost_tune/graph.rs

Improve error messages for dm/md device and ghostscript related failures.
This isn't a great solution but better than before. #254 #256

Better error messages

---

rd-agent/src/misc/biolatpcts.py

The new version uses block_rq_complete TP instead of kprobing
blk_account_io_done() which should make it a lot more robust against kernel
changes and compiler inlining differences.

agent: Update biolatpcts.py to the latest version

---

resctl-bench/src/bench/iocost_tune.rs
resctl-bench/src/main.rs

Signed-off-by: Gustavo Noronha Silva <gustavo.noronha@collabora.com>

hwdb: add option to generate for specific fwrev

---

Cargo.lock
rd-util/src/storage_info.rs

While at it, drop no-longer-necessary unsafe() in storage_info.

cargo update

---

rd-util/src/storage_info.rs

For root filesystems, proc_mounts crate often fails to find the actual underlying device. e.g. For root filesystem, the source usually points to `/dev/root` which doesn't always exist. `findmnt` already has a bunch of heuristics to resolve the actual device. Let's use that instead.

rd-util: Use `findmnt` to map path to devname

---

Cargo.lock
rd-agent-intf/Cargo.toml
rd-agent-intf/src/slices.rs
rd-agent-intf/src/sysreqs.rs
rd-agent/Cargo.toml
rd-agent/src/report.rs
rd-agent/src/slices.rs
resctl-demo/Cargo.toml
resctl-demo/src/doc.rs
resctl-demo/src/graph.rs

Update enum-iterartor dependency to the latest

---

resctl-bench/src/base.rs

Some Linux distributions (e.g., Debian) use a kernel release string without minor or patch numbers (e.g., "6.14-amd64"), causing incorrect detection of shadow inode protection support:
[WARN] base: Failed to parse kernel version string 6.14-amd64
Improve version parsing to handle such cases correctly.

bench: improve shadow inode protection detection
