facebookexperimental/resctl-demo

rd-agent-intf/src/cmd.rs, rd-agent/src/hashd.rs, rd-hashd-intf/src/args.rs, rd-hashd-intf/src/lib.rs, rd-hashd-intf/src/params.rs, resctl-demo/src/doc.rs, resctl-demo/src/doc/comp.cgroup.mem.thrash.rd, resctl-demo/src/doc/doc-format.rd, resctl-demo/src/doc/markup_rd.rs
Several interface modules define pub const default parameters and then use
them to initialize default(). The intention was making the default values
easily accessible from other places but that can easily be achieved by
providing pub static default() instance. Let's drop the consts so that
default() struct is the source of truth.
* Drop rd_hashd_intf Args and Params pub consts and provide DFL_ARGS and
DFL_PARAMS.
* The above removes the link between file_addr_stdev and anon_addr_stdev.
Update agent and demo so that they distinguish the two.
* Drop rd_agent_intf::HashdCmd::DFL_LOG_BPS. Instantiate default() when
needed.
=> hashd, agent, demo: drop some pub const default parameters

rd-agent-intf/src/cmd.rs, rd-hashd-intf/src/params.rs
So that all default params come from the same place.
=> hashd, agent: move default log_bps param to rd_hashd_intf::Params

rd-agent/src/misc/io_latencies.py, rd-agent/src/misc/iocost_coef_gen.py
These sort directives aren't necessary anymore -- it's disabled via an internal config file now.
=> Remove deprecated sort directives

rd-agent/src/side.rs, resctl-demo/src/doc/intro.sysreqs.rd
`bc` is needed for allmodconfig linux build but isn't automatically
installed on e.g. arch linux. Add it as an explicit dependency.
=> agent, demo: add `bc` to dependency

Cargo.lock, rd-agent/Cargo.toml, rd-agent/src/slices.rs, util/Cargo.toml, util/src/systemd.rs
While the error and enum handlings are a bit painful, for the features that
util::systemd uses, rustbus can be a drop-in replacement for dbus-rs
allowing us to shed the dependency on libdbus.
=> util: switch from dbus-rs to rustbus

util/src/systemd.rs
=> util: oops, s/dbg/debug/

resctl-demo/src/command.rs
55b9a1794e22 ("agent: add support for cmd::bench_hashd_args") incorrectly
changed cmd.bench_hashd_seq update so that the value is changed iff the next
value is higher making it impossible to stop hashd benchmarks. Fix it by
applying the change whenver the current value doesn't equal the next.
=> demo: fix turning off hashd benchmark

resctl-demo/src/main.rs
Recent cursive change means that hooking into WindowResize event needs a bit
of special magic. Implement the suggested workaround.
=> demo: fix layout update on resize

resctl-bench/src/bench/storage.rs
Up phase alone somtimes fails to achieve stable memory configuration.
=> bench: storage: run both Up and Bisect phases to gauge available memory

rd-agent-intf/src/report.rs, rd-agent/src/hashd.rs, rd-agent/src/report.rs, rd-hashd-intf/src/report.rs, rd-hashd/src/bench.rs, resctl-bench/src/bench/storage.rs
Which likely is close to what the device would see in stable state serving
the determined memory footprint.
=> bench: storage: report io rwbps during the final refine rounds

rd-agent-intf/src/report.rs, rd-agent/src/hashd.rs, rd-agent/src/report.rs, rd-hashd-intf/src/report.rs, rd-hashd/src/bench.rs, resctl-bench/src/main.rs
rd-hashd was reporting mem_probe_frac and rd-agent was incorrectly
multiplying that with bench.json::mem_size which can be zero and is wrong
even when not. Fix and simplify it by making rd-hashd report mem_probe_size
instead.
=> fix hashd bench mem_probe_size reporting

rd-agent/src/misc.rs, rd-agent/src/report.rs, rd-hashd-intf/src/args.rs, rd-hashd/src/bench.rs, resctl-bench-intf/src/args.rs, resctl-bench/src/bench/hashd_params.rs, resctl-bench/src/bench/iocost_params.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/storage.rs, resctl-bench/src/job.rs, resctl-bench/src/main.rs, resctl-bench/src/run.rs
iocost-qos bench can run for a really long time and can fail depending on the IO device behavior. Losing the results wastes a lot of time and energy. Address it by:
* Make --incremental mode default and make iocost-qos save result in the buffering area as each run completes so that a result is never lost.
* iocost-qos bench now can retry on rd-agent failures and produce output with failed runs.
* rd-agent now retries launching biolatpcts after bcc init failures.
=> Incremental bench result saving and bcc failure retries

rd-agent-intf/src/bench.rs, resctl-bench-intf/src/args.rs, resctl-bench-intf/src/jobspec.rs, resctl-bench/src/bench.rs, resctl-bench/src/bench/hashd_params.rs, resctl-bench/src/bench/iocost_params.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/storage.rs, resctl-bench/src/job.rs, resctl-bench/src/main.rs, resctl-bench/src/run.rs
Previously, when a bench needed the result from another bench, it had to insert the spec for the nested bench into the scheduled specs list from the preprocess hook before bench runs start. This was inflexible (can't make dynamic decisions) and often required duplicate parsing and other processing. This pull modularizes job handling, implements nested execution support and replace preprocessing with straight-forward nested runs.
=> Allow bench runs to be nested

resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/iocost.rs
This reverts commit bf6c9bc2fbfcec138eca7753067069c68218f705.
The lowered floor introduces another inflection point in some graphs
confusing line fitting. If we wanna support slow hard drives, the right
thing to do would be applying lowered min perf to only hard drives.
=> Revert "bench: lower ABS_MIN_IO_PERF"

rd-agent/src/misc/iocost_coef_gen.py
Revert ioengine to libaio as io_uring is not stable
=> iocost_coef_gen.py: Revert ioengine to libaio as io_uring is not stable

rd-agent/src/report.rs
With resctl-bench, they can trigger all the time. Tone them down to debug.
=> agent: quiet memory.stat read error warnings which trigger spuriously

resctl-bench-intf/src/args.rs, resctl-bench-intf/src/lib.rs, resctl-bench/src/bench.rs, resctl-bench/src/bench/hashd_params.rs, resctl-bench/src/bench/iocost_params.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/merge_info.rs, resctl-bench/src/bench/protection.rs, resctl-bench/src/bench/storage.rs, resctl-bench/src/main.rs
This avoid the clap bug around positional argument and subcommand and prepares for "doc" subcommand which won't need the result file specified.
=> Make the result file an option instead of a positional argument

resctl-bench/src/job.rs, resctl-bench/src/study/iolat.rs
* I'm not sure how it happened but study code panicked on incomplete iolat
map. Make the code check the latency being read is actually available.
* If an incremental benchmark fails while computing the result after all
steps are complete, the result produced after running it again ends up
with no sysreqs_report because rd-agent is never started on the run which
produces the result. The generic code has a fallback code to cycle
rd-agent to produce sysreqs_report for such cases but it wasn't being
activated correctly. Fix it.
=> bench: make benchmarks more resilient

resctl-bench-intf/src/jobspec.rs, resctl-bench/src/base.rs, resctl-bench/src/bench/hashd_params.rs, resctl-bench/src/bench/iocost_params.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/protection/mem_hog_tune.rs, resctl-bench/src/bench/storage.rs, resctl-bench/src/job.rs, resctl-bench/src/main.rs, resctl-bench/src/run.rs, util/src/iocost.rs
Improve how bench params are applied and committed persistently so that it's simpler and consistent across different benchmarks and the result from e.g. storage bench can be easily applied to subsequent benchmarks.
=> Improve [rb-]bench.json handling

resctl-bench/src/base.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/iocost.rs, resctl-bench/src/run.rs
QoS overrides are clobbered by set_hashd_mem_size() because they were being
applied without updating the rctx's base QoS params. Fix it by always
applying through rctx. While at it, add bench param revert mechanism and
make iocost-qos use it as iocost-qos applies multiple different hashd and
iocost QoS parameters and we don't wanna keep them applied afterwards.
=> bench: iocost-qos: fix QoS override applications

rd-agent/src/misc/biolatpcts.py, rd-agent/src/side/memory-balloon.py, rd-agent/src/side/read-bomb.py
Some distros are getting rid of un-versioned python alias.
=> agent: make python shebangs consistent

rd-agent/src/side/inodesteal-test.py
inodesteal-test.py was prone to incorrectly report success inside VMs. Bump
inactive page cache size. This seems to make the detection a lot more
reliable.
=> agent: inodesteal-test.py: bump inactive page cache size

rd-agent/src/side/inodesteal-test.py
In some installations, the messages get buffered even though they're going
through stderr. Flush explicitly.
=> bench: inodesteal-test.py: add flush=True to progress messages

rd-agent-intf/LICENSE, rd-agent/LICENSE, rd-hashd-intf/LICENSE, rd-hashd/LICENSE, rd-util/LICENSE, resctl-bench-intf/LICENSE, resctl-bench/LICENSE, resctl-demo/LICENSE
Needed to package `resctl-demo` in Fedora. Not sure if we also need to add something to `Cargo.toml` for these to be included, or if just copying the files in is enough.
=> Include LICENSE in all crates

Cargo.lock, rd-agent/Cargo.toml, rd-util/Cargo.toml
Needed to package `resctl-demo` in Fedora. `cargo test` still passes.
=> Bump sysinfo to 0.18

rd-agent/src/cmd.rs, rd-agent/src/main.rs
rd-agent was overwriting iosched unconditionally and didn't restore them
afterwards. Fix it.
=> agent: restore iosched on exit and don't override it if passive=io

Cargo.lock, rd-agent/src/main.rs, rd-util/src/journal_tailer.rs, resctl-demo/Cargo.toml, resctl-demo/src/doc.rs, resctl-demo/src/doc/markup_rd.rs, resctl-demo/src/graph.rs, resctl-demo/src/journal.rs, resctl-demo/src/main.rs
Update cursive to 0.16 and use the new features:
* Replace the custom indexing and iterated updates for multiple elements with the same name with `call_on_all_named()`.
* Implement incremental log view update.
While at it, fix slider bar formatting breakage.
=> Update cursive to 0.16 and use the new features

Cargo.lock, resctl-bench/Cargo.toml, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/iocost_tune/merge.rs
This is needed for the Fedora packaging. Note: I'm not entirely sure `ContinuousCDF` is the right replacement for `Univariate`, please double check that before merging. Thanks!
=> Update statrs to 0.15

Cargo.lock, rd-agent/src/main.rs, resctl-bench/Cargo.toml, resctl-bench/doc/shadow-inode.md, resctl-bench/src/base.rs, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/iocost_tune/merge.rs, resctl-bench/src/run.rs
The test takes too long and isn't completely reliable. Work around by:
* Assume fbks and kernels >= v5.15 are protected.
* Add a pseudo module param marker in the resctl-demo kernel so that it can
be tested quickly.
=> bench: improve shadow inode protection handling

rd-hashd-intf/src/params.rs, rd-hashd/src/bench.rs, rd-hashd/src/hasher.rs
So that hashd can generate non-sequential file writes.
=> hashd: add file_write_frac parameter

resctl-bench/src/base.rs, resctl-bench/src/bench.rs, resctl-bench/src/bench/hashd_params.rs, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/storage.rs, resctl-bench/src/run.rs
Fake cpu load hashd benchmarks are used to evaluate storage performance in
isolation. Let's scale the max RPS along with mem_share so that larger
memory profile means tougher IO workload so that users have the ability to
scale up the benchmark if necessary.
The scaling factor is set up so that the max RPS remains at 2000 when the
default 16G memory profile.
=> Scale rps with memprof

resctl-bench-intf/src/args.rs, resctl-bench/src/base.rs
It sometimes triggers oomd kills and fails incorrectly. While at it, add
command line parameters to force/skip shadow inode protection test.
=> bench: disable oomd while testing shadow inode protection

resctl-bench/doc/iocost-tune.md, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/study.rs
iocost-tune was using a[MOF]=max points as the upper limits when calculating solutions with the rationale that going higher doesn't add to bw increase for hashd while potentially worsening control quality. However, this is only true when the system is running only one instance of hashd. As such, all it says about is the ratio between hashd's latency requirement and the device's average completion latency. If the latency requirement changes, more instances of hashd run on the machine, or something else shares the machine, the a[MOF]=max point doesn't really give any indication on where "useful" bandwidth ends.
Let's drop it as upper bound and update the solution rules as follows:
* bandwidth: The maximum vrate at which hashd can still be protected.
* isolated-bandwidth: The maximum vrate …
=> Iocost tune solutions

resctl-bench/src/base.rs
In study mode, no benchmark is actually being run and the bench file doesn't
need to be and can't be updated (the path is not initialized). Silently
bypass apply_bench_knobs() if bench_knobs path is not set to avoid causing
spurious failures in study mode.
=> bench: ignore bench updates in study mode

CONTRIBUTING.md, resctl-bench-intf/src/args.rs, resctl-bench/README.md
The default branch name was not updated in some places. Fix it.
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
=> Fix default branch name

Cargo.lock, resctl-bench-intf/Cargo.toml, resctl-bench-intf/src/args.rs, resctl-bench/Cargo.toml, resctl-bench/src/lambda.rs, resctl-bench/src/main.rs
This change allows resctl-bench to be executed as an AWS lambda
function to validate result files and create issues on github
for them.
AWS lambda expects a `bootstrap' binary and does not give it any
arguments. For that reason we first look at our executable name to
decide whether we should be running as a lambda function and re-exec
ourselves with the appropriate arguments.
The lambda function's goal is to validate and submit benchmark results
to github as issues. The benchmark file is uploaded to S3.
Signed-off-by: Gustavo Noronha Silva <gustavo.noronha@collabora.com>
=> Server-side automation for results submission

Cargo.lock, rd-util/Cargo.toml
This fixes build on machine w/ newer libgit2.
=> util: relax version requirement of the vergen crate

Cargo.lock, rd-util/src/lib.rs, resctl-bench-intf/src/args.rs, resctl-bench/Cargo.toml, resctl-bench/src/lambda.rs, resctl-bench/src/main.rs
The upload subcommand is the client for the AWS lambda function. It
validates the result file and uploads it to the function for an issue to
be created automatically.
Optional parameters allow the user to include their email address or
github handle in the issue.
The lambda has been improved to use that data and to be better at
identifying duplicates.
Signed-off-by: Gustavo Noronha Silva <gustavo.noronha@collabora.com>
=> bench: add upload subcommand

rd-hashd/src/bench.rs, rd-hashd/src/hasher.rs, rd-hashd/src/testfiles.rs, rd-util/src/anon_area.rs, resctl-bench/doc/iocost-tune.md, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/iocost_tune/graph.rs, resctl-bench/src/bench/iocost_tune/merge.rs, resctl-bench/src/job.rs, resctl-bench/src/main.rs, resctl-bench/src/merge.rs, resctl-bench/src/run.rs
There are a couple important changes around iocost-tune aMOF handling.
* The aMOF criterion was isol-01 being above 90%. This unfortunately turned out to be too strict for a lot of devices and we end up solutions which are very pessimistic or outright no solutions on lower end devices. Another problem is that it makes the benchmark too sensitive to disturbances which may not be coming from the IO device at all. Relax the criterion to isol-05, which is still a pretty strong guarantee while making the benchmark more robust.
* aMOF is one of the most important metrics that iocost-tune uses in determining the parameter solutions. However, because of the limited line fitting that it could do, it wasn't very good at utilizing it - e.g. some, usually high performing, devices show aMOF graph …
=> bench: iocost-tune: Improve aMOF handling

rd-hashd/src/bench.rs, rd-hashd/src/hasher.rs, rd-hashd/src/testfiles.rs, rd-util/src/anon_area.rs, resctl-bench/doc/iocost-qos.md, resctl-bench/doc/iocost-tune.md, resctl-bench/src/bench/iocost_qos.rs, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/bench/iocost_tune/graph.rs, resctl-bench/src/bench/iocost_tune/merge.rs, resctl-bench/src/bench/protection.rs, resctl-bench/src/bench/protection/mem_hog_tune.rs, resctl-bench/src/job.rs, resctl-bench/src/main.rs, resctl-bench/src/merge.rs, resctl-bench/src/run.rs, resctl-bench/src/study/rstat.rs
There are a couple important changes around iocost-tune aMOF handling.
The aMOF criterion was isol-01 being above 90%. This unfortunately turned out to be too strict for a lot of devices and we end up solutions which are very pessimistic or outright no solutions on lower end devices. Another problem is that it makes the benchmark too sensitive to disturbances which may not be coming from the IO device at all. Relax the criterion to isol-05, which is still a pretty strong guarantee while making the benchmark more robust.
aMOF is one of the most important metrics that iocost-tune uses in determining the parameter solutions. However, because of the limited line fitting that it could do, it wasn't very good at utilizing it - e.g. some, usually high performing, devices show aMOF graph which …
=> More forgiving amof

rd-agent/src/cmd.rs, rd-agent/src/main.rs, resctl-bench/README.md, resctl-bench/doc/common.md, resctl-bench/examples/prot-iocost-off-on-format.txt, resctl-demo/src/doc/intro.sysreqs.rd
There's no tangible benefits to using mq-deadline and it gets in the way on
high iops devices. Use none iosched instead.
=> agent: Enforce none iosched instead of mq-deadline

rd-agent/src/misc/iocost_coef_gen.py
On hard disks or other devices which don't support trim, the trim commands
will fail. We still wanna proceed with the benchmark. Ignore the failures.
=> agent: iocost_coef_gen.py: Allow trim commands to fail

rd-agent/src/main.rs, resctl-bench/doc/iocost-tune.md, resctl-bench/src/bench.rs, resctl-bench/src/bench/iocost_tune.rs, resctl-bench/src/job.rs, resctl-bench/src/lambda.rs, resctl-bench/src/merge.rs, resctl-bench/src/merge/info.rs
I am wondering if we should just show the minimum number of points and the maximum for ouliers and errors instead of showing all of the solutions. What information would you like to have here? This is what it looks like right now:
```
==========================================================================================
[0] iocost-tune
version: 2.2
memory-profile: 16
storage: Samsung SSD 970 PRO 512GB
classifier: dither,vrate-max=125
sources:
+ ../result-files/2.2/970pro.json.gz
==========================================================================================
[MOF]
23 points, 0 outliers, error: 0.005026878511151166
[isol]
23 points, 0 outliers, error: 0.002473790887859725
[aMOF]
23 points, 0 outliers, error: 0.010598882713881336
[aMOF-delta]
23 points, 0 outliers, error: …
```
=> Merge summary

resctl-bench/src/bench/iocost_tune.rs
Having a single datapoint causes fit_lines(): best_lines(DataLines) invalid input order exception as the expectation is an array of monotonically increasing (x) Datapoints. The correct output of fit_lines() for a single datapoint is a mean flat line passing through that datapoint.
=> bench: iocost-tune: fit_lines() single datapoint handling

resctl-bench/src/bench/iocost_tune.rs
The high level formatting code relied on the rule names matching the
solutions, and on there being at least 4 solutions, which is not
always the case on files in the wild. Gracefully handle that.
Signed-off-by: Gustavo Noronha Silva <gustavo.noronha@collabora.com>
=> Handle missing solutions on high level formatting

resctl-bench/src/job.rs
Simple change to mark the version of resctl-bench used to produce the result files.
Test
```
* ./build-and-tar.sh
* Sanity
./target/release/resctl-bench -r target/resctl-bench-result_2022_07_26-19_38_06.json format iocost-tune 
==========================================================================================
[iocost-tune 2.2.4 result] 2022-07-26 19:13:40 - 19:13:40
...
```
=> bench: Adding version information to result header 

resctl-bench/src/bench/iocost_tune.rs
This is basically to adapt the hwdb file that gets generated to requests made by the systemd maintainers. I am also including a commit to add the rlat solutions as we had agreed and I forgot for the initial merge. This is what the hwdb entry for a device looks like:
```
block:*:name:MZUL2256HCHQ-00AFB:
IOCOST_SOLUTIONS=isolation isolated-bandwidth bandwidth naive
IOCOST_MODEL_ISOLATION=rbps=626708081 rseqiops=27119 rrandiops=26638 wbps=138402498 wseqiops=3257 wrandiops=3208
IOCOST_QOS_ISOLATION=rpct=0.00 rlat=1997 wpct=0.00 wlat=50837 min=100.00 max=100.00
IOCOST_MODEL_ISOLATED_BANDWIDTH=rbps=997831946 rseqiops=43179 rrandiops=42412 wbps=220361662 wseqiops=5186 wrandiops=5107
IOCOST_QOS_ISOLATED_BANDWIDTH=rpct=0.00 rlat=2213 wpct=0.00 wlat=61487 min=100.00 max=100.00 …
```
=> Hwdb adjustments

resctl-bench/src/bench/iocost_qos.rs
Currently, if we interrupt `resctl-bench` when it's creating the result file for the first time, it'd produce an incomplete result with null `record` field. Something like this:
```
[
{
"spec": {
"kind": "iocost-params",
"id": null,
"passive": null,
"props": [
{}
]
},
...
"record": null,
"result": null
}
]
```
With such json file, if we try rerun `resctl-bench` it would crash since we're reusing `record` field unchecked. This pr fixes that.
=> Check if  is set before parsing the field

.github/workflows/ci.yaml, .github/workflows/lambda.yaml
Build the lambda function, package it as expected by AWS lambda, then update it on AWS.
For now this is only triggered manually, so that the update can be performed only when it makes sense to the developers. In the future we can make a release being tagged trigger this workflow.
=> New workflow to deploy the lambda function

Cargo.lock, resctl-bench/Cargo.toml, resctl-bench/src/lambda.rs, resctl-bench/src/main.rs
Detail:
Lambda function was panicking while deserilaizing the request and creating event which is passed to lambda runtime handler. This is fixed by using actual function url as event types and updating to latest aws modules.
=> Update to latest AWS sdk and fix deserialize issue

rd-agent-intf/src/args.rs, rd-hashd-intf/src/args.rs, rd-util/src/json_file.rs, rd-util/src/lib.rs, resctl-bench-intf/src/args.rs, resctl-demo/src/main.rs
~If environment variable LOG_DUMP_FILE=<filename>~
A new option --log-file is added to command line args. When filename is specified, the logs are also dumped to this file. Terminal output are logged as usual.
This logfile can be used for debugged purpose.
=> Enable resctl-bench log dumping to file.

resctl-bench/src/lambda.rs
Update this to use the new account
=> resctl-bench: update S3 bucket in the lamba

Cargo.lock, resctl-bench/Cargo.toml, resctl-bench/doc/lambda.md, resctl-bench/src/lambda.rs
A new github app "iocost-issue-creater" is created and installed in iocost-benchmark organization which has a permission to file issue on iocost-benachmarks repository.
When a user uploads the benchmark result with lambda url, lambda saves the benchmark result in aws s3 bucket and create a issue in iocost-benchmarks projects.
=> Integrate github app workflow with lambda.

Cargo.lock, rd-agent-intf/Cargo.toml, rd-agent/Cargo.toml, rd-hashd-intf/Cargo.toml, rd-hashd/Cargo.toml, rd-util/Cargo.toml, resctl-bench-intf/Cargo.toml, resctl-bench/Cargo.toml, resctl-demo/Cargo.toml
Now crates with version 2.2.4 is released in crates.io, so we need to update dev version to next version.
=> Move development version(main branch) from 2.2.4 to 2.2.5

resctl-demo/Cargo.toml
These packages are interdependent and their versions need to match. Explicitly specify the versions.
=> resctl-demo: Explicitly specify cursive dep versions

rd-util/src/lib.rs
vergen generates VERGEN_IDEMPOTENT_OUTPUT when built out of tree. Let's handle that.
=> rd-utils: Improve VERGEN_GIT_SHA handling

resctl-bench/src/lambda.rs, resctl-bench/src/main.rs
- Catch exceptional scenarios and provide error messages instead of panicking
- Enhance AWS lambda error logs
- Return errors in the lambda function as error responses to the client
=> Improve UX for the lambda workflow (`upload` and `lambda`)

resctl-demo/Cargo.toml, resctl-demo/src/doc.rs, resctl-demo/src/main.rs
Removed `cursive_buffered_backend` dependency as `cursive` v0.21 includes its own buffered backend implementation.
Updated `cursive` and `cursive-tabs` to recent versions.
=> resctl-demo: use native buffer from cursive

Cargo.lock, rd-hashd/Cargo.toml, rd-hashd/src/bench.rs, rd-hashd/src/hasher.rs
Update pid dependency from 3.0 to 4.0.
Allows building with packaged version on Debian.
=> rd-hashd: update pid from 3.0 to 4.0

rd-util/Cargo.toml, rd-util/src/systemd.rs
Using the blocking versions of zbus, when vendoring it for a monorepo, affects other crates that might be trying to be leaner - and zbus documentations discourages using those functions anyway.
This diff just does the blocking internally inside rd-util so we don't have to use the blocking-api feature of zbus.
=> Use async zbus and block internally in rd-util
